url: https://rebargen.dedunu.info
baseurl: /

# Site settings
title: Rebargen Engineering
email: hello@rebagen.eng
description: "A decade of precision rebar detailing, delivering accuracy you can build on"


# Team names, titles and social links
people:
- name: Malith Rukshan
  pic: 2
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 12 
  - line: Kelaniya Sri Lanka

# Build settings
markdown: kramdown
permalink: pretty